### PR TITLE
C bindings

### PR DESCRIPTION
**Pull request by mattmassicotte**
This PR adds a Makefile that can build and install static/dynamic libraries and headers suitable for C-compatible language clients. This is just automation that makes the parser easier to use. It does not affect the parser functionality in any way.

All the components are standardized and parser-agnostic aside from the name, version, and some informational comments in the .pc file.

The backstory: tree-sitter/tree-sitter#1488
The first implementation: tree-sitter/tree-sitter-go#56

### CODE REVIEW

**Comment by mattmassicotte** [comment]
Hello! Just wondering if there is anything I can help out with here. Would be happy to!

**Comment by aryx** [comment]
hmm the windows CI are failing. I think it's similar to https://github.com/tree-sitter/tree-sitter-java/pull/106
where we need to switch to nodejs 16.

**Comment by mattmassicotte** [comment]
Ok great! I've made https://github.com/tree-sitter/tree-sitter-ruby/pull/206

**Comment by mattmassicotte** [comment]
However, I would like to update the content here slightly, so please hold off for a just moment while I do that.

**Comment by mattmassicotte** [comment]
Updated Makefile and input files to be generic to the parser name, which makes it possible to just copy across parsers.

Also, this CI failure appears to be related to CI configuration (https://stackoverflow.com/questions/57541402/node-gyp-configure-got-gyp-err-find-vs), and wasn't affected by this change.

What do you think?

**Comment by mattmassicotte** [comment]
Thank you so much!

**Pull request merged**
