### PR TITLE
Add ruby spec examples and run them as part of ci

### PR DESCRIPTION
**Pull request by tclem**
Adds https://github.com/ruby/spec to the project (just as a subtree, open to doing this as a submodule too) and wires up tests to parse all the files in there.

### CODE REVIEW

**Comment by tclem** [comment]
OK @maxbrunsfeld. I think this is good to go for a first pass. I fixed a few errors in the grammar that popped up and right now have it set up to only run a few of the examples in the `language` directory.

There are a bunch of issues related to unicode characters in things like symbols and strings, but I think some tree-sitter improvements will be necessary to tackle those. Filed https://github.com/tree-sitter/tree-sitter/issues/95 to that affect.

Last, ci seems to have some trouble with the glob path expansion of `tree-sitter parse examples/**/*.rb -q -t`. There might be some argument limit size that I don't know about? I was also seeing inconsistent results when running `tree-sitter` parse on multiple paths like that so the script I included just does them one at a time (which is slow, but consistent).

**Comment by maxbrunsfeld** [comment]
> Last, ci seems to have some trouble with the glob path expansion of `tree-sitter parse examples/**/*.rb -q -t`

I don't think bash supports the `**` operator in glob patterns; I think that's an extension that ruby and several other globbing systems added. You can use multiple glob patterns though, and you can use multiple `*` operators, like `examples/*/*.rb`. Would that work? It seems like a shame to make repeated calls to `tree-sitter parse`.

**Comment by maxbrunsfeld** [comment]
Also, should we remove the non-ruby files from ruby_spec, like the changelog and stuff, or do you think there's value in taking the repo wholesale?

**Comment by tclem** [comment]
> Also, should we remove the non-ruby files from ruby_spec, like the changelog and stuff, or do you think there's value in taking the repo wholesale?

I was thinking we probably want to keep enough to show attribution to that project. I was using `git subtree` to quickly pull in that project. We can easily pull the latest like this now:

`git subtree pull --prefix examples/ruby_spec https://github.com/ruby/spec master --squash`

**Comment by tclem** [comment]
> I don't think bash supports the `**` operator in glob patterns

A yes, you're correct. Even with just `*/*.rb` I'm seeing inconsistent results with back to back runs of tree-sitter parse. Different files fail to parse each time, but don't fail when run in isolation. Not sure what's up, but as discussed in chat, let's get on the [latest API](https://github.com/tree-sitter/tree-sitter-ruby/pull/53) before we troubleshoot that. I'll push a proposal for just running out of the "test" node in package.json now.

**Comment by tclem** [comment]
OK, switched to using ruby/spec as a submodule and manually excluding files we don't want to run in `script/parse-examples`. I think this is good for a first pass. We can circle back to sort out why running `tree-sitter` parse with a list of paths fails inconsistently.

**Pull request merged**
