### PR TITLE
package.json: expand to include electron 4.0.4

### PR DESCRIPTION
**Pull request by maletor**
https://github.com/lgeiger/node-abi/blob/master/index.js#L71
https://github.com/rubyide/vscode-ruby/issues/486

### CODE REVIEW

**Comment by wingrunr21** [comment]
While we are at it Electron 5.0 should be added here so we get ABI 70 support. We may be able to drop Electron <= 2 support though? Not sure if you are using it @maxbrunsfeld 

Also looking at moving this over to the WASM build in the future so appreciate the support here

**Comment by Arcanemagus** [comment]
Electron 2.0 support is still needed for Atom (till the Electron 3 builds hit stable with v1.39.0), 1.8 support can _probably_ be dropped though.

**Comment by maletor** [comment]
@Arcanemagus, ready to merge?

**Comment by maxbrunsfeld** [comment]
It's actually fine to drop Electron 2.0 support, since Atom doesn't need prebuilt binaries. We build a lot of modules from source during the Atom build. Can Electron 4.0.0 support be dropped too? Is 4.0.4 a bugfix release from 4.0.0 with a bumped ABI version?

The reason it matters is that these builds have timed out in the past from trying to compile too many binary versions.

**Comment by maxbrunsfeld** [comment]
I would say that we should drop Electron 1.8 and 2.0, and unless anyone is aware of a good reason to support 4.0, we should drop that too.

**Comment by wingrunr21** [comment]
We can drop 4.0 support from our end. I'll just set a minimum VSCode version on the extension when I upgrade this.

**Comment by maletor** [comment]
4.0.4 is the minimum [relevant version number](https://github.com/lgeiger/node-abi/blob/master/index.js#L71) where the ABI version changes.

**Comment by wingrunr21** [comment]
4, 4.0.4, and 5 is only 3 ABI versions so shouldn't cause the timeout issue

**Comment by maxbrunsfeld** [comment]
Ok, I'm cool with keeping 4.0, 4.04, and 5.

**Comment by wingrunr21** [comment]
Any way to get this merged and a release cut?

**Comment by maletor** [comment]
We must be close?

**Comment by minkir014** [comment]
@wingrunr21 you are a contributer. why don't you merge that?

**Comment by maxbrunsfeld** [comment]
@maletor Just restating the comments I made above - We can't build all of these versions, or CI will be very likely to time out. We can drop support for some older versions, and **keep only 4.0, 4.0.4, and 5.0**.

Since this is your PR, can you make that change?

**Comment by wingrunr21** [comment]
@minkir014 I don't have commit privs here. Contributor just means I've contributed to the project in the past.

+1 to @maxbrunsfeld's comments. @maletor can you make those changes? Otherwise I'll open a new PR with the correct changes.

**Comment by bradens** [comment]
Is there a workaround for people coming here from https://github.com/rubyide/vscode-ruby/issues/486? This bug is pretty bad for people working in ruby all day.

**Comment by wingrunr21** [comment]
I just posted a workaround in that issue.

If @maletor doesn't get time to update the PR before tonight I'll open a new one this evening.

**Comment by wingrunr21** [comment]
That works too. Thanks @maxbrunsfeld

**Pull request merged**
