### PR TITLE
Bring ruby grammar up to date, green tests, faster generate/build

### PR DESCRIPTION
**Pull request by tclem**
Going to track work as I go to bring tree-sitter-ruby up-to-date and get the tests passing again. ~~~With a couple of fixes here and in tree-sitter, tests are currently passing, but generate times are very slow (on the order of 20mins).~~~ EDIT: Back to acceptable generate/build times.
- [X] Depends on https://github.com/tree-sitter/tree-sitter/pull/42

cc @maxbrunsfeld

### CODE REVIEW

**Comment by tclem** [comment]
This PR is now tracking a bunch of important changes/improvements as I work to develop out the grammar.

- With advice from @maxbrunsfeld, I've focused in on supporting only a small number of ruby's crazy unbalanced delimiters that can be used for % string and regex literals. The full list of these is one cause of the long generate and build times as we get an explosion of parse and lex states. We picked a small number of the difficult ones (e.g. `#` which also denotes interpolation) to support and will consider adding back in the full list at a later date.
- Slightly better handling of precedence for regex and string bodies. We now only bump precedence for top level regex definition because the `/` character to define a regex is also divide and the divide by math assignment, both of which have the fairly high `MULTIPLICATIVE` precedence.
- Refactoring and bug fixes for regexBody and stringBody which both now better support the various permutations of clashing characters like when you delimit your % string with `#` and then try to use interpolation (not allowed). One item of note here is that we are constructing a single Regex for the contents of a string or regex literal instead of using the tree-sitter DSL (things like `choice`, `seq`) for performance reasons. This approach gives us something like 1.9k instead of 9.6k states in the lex state machine.
- Bug fix for comments following multi line comments.
- Bug fix for `=` in multi line comments.
- Removed the extraneous `condition` production.
- New support for math assignments (e.g. `x *= 5`)
- New support for conditional assignments (e.g. `x ||= foo`)

**Comment by joshvera** [comment]
Looks good to me 👍. Do you know which terms we still need to parse?

**Comment by maxbrunsfeld** [comment]
:ship: Looks great. Nice work @tclem!

**Comment by tclem** [comment]
> Do you know which terms we still need to parse?

Let me open an issue to document and discuss what's left. There's no official spec for Ruby and there are syntactic differences even between minor releases of MRI, but I have a couple of resources I've been using.

**Pull request merged**
